### ISSUE TITLE
Maybe a little mistake in this line of code

### ISSUE THREAD

**Issue by shrrr** [luo-ziyuan/Imaging-Interiors#1]
https://github.com/luo-ziyuan/Imaging-Interiors/blob/4659115e35d6e904e697f3fe687fe754b220eff5/run_isp_double_MLP_L1.py#L79

If we want to caculate the norm of xi_E_inc, I think this line of code should be as follows
```Python
re['norm_xi_E_inc'] = torch.mean(xi_E_inc.real ** 2 + xi_E_inc.imag ** 2)
```

BTW, How is the **Random Spatial Sampling** method implemented in this code?

Hope for your reply. Thank you!

**Comment by luo-ziyuan** [comment]
Thank you very much for pointing out this issue. We have corrected it in the latest version.

The Random Spatial Sampling is implemented by simply setting the parameter `--sample_perturb`. 

Thanks a lot! ^^

**Comment by shrrr** [comment]
Get it, thank you for your answer! 

May I ask what specific modifications are made to the 3D EISP in your implementation?

Thank you !

**Comment by luo-ziyuan** [comment]
Hi, for the 3D case, the green's function is slightly changed. You can refer to the Eq. (2.8) in this paper ([https://arxiv.org/pdf/1911.10289](https://arxiv.org/pdf/1911.10289)) for implementation, compared to 2D equations such as Eq. (1) in [this paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8476623).

**Comment by shrrr** [comment]
Okay, got it. Thank you very much！
